### PR TITLE
General fixes

### PR DESCRIPTION
**Pull request by ghost**
Fixes collision for the road near the Taco Bell lot, deletes some useless lines/files, adds the missing textures from the thread, and updated the .terrn file to match the 0.4 version.

@DarthCainRor: Please add a note to your thread that this map is now for 0.39+ as it now hits 0.38's collision limit.

### CODE REVIEW

**Comment by DarthCainRor** [comment]
Awesome. Thanks for that. Been meaning to add it, along with some of my other recent changes, but work's been getting to me.

**Comment by DirtGamer301** [comment]
"if you have lots of objects, you might want to increase the collision buffer size so everything stays contractible. The default is 100000.
collision-tris 100000"

From: http://www.rigsofrods.com/wiki/pages/Terrn_file_description

AFAIK adding this to the terrn file should increase the collision limit for 0.38 and therefore be usable again :)

**Comment by ghost** [comment]
@DirtGamer301 Both the 0.4 and 0.39 versions use `collision-tris`; This feature was added in 0.39.0, it doesn't do anything in 0.38 :grinning:

**Comment by DarthCainRor** [comment]
Wait.. The Old Highwaypiece-col was actually a simplified version of the other. ~~Would be better to find what's causing the issue rather than just using the standard highway mesh~~

Edit: I see the problem. Will fix when I get off work

**Comment by ghost** [comment]
Yeah I know, when I compared both meshes there wasn't many changes so I decided to just reuse the original highway mesh instead of dealing with no collision :smile:  Would be great if you could fix the current mesh. I didn't notice any framerate drops when using the standard mesh though.

**Comment by DarthCainRor** [comment]
Its got about 10k less polies. From the bridges being simpler. The collision one lacks the pipe rails and separate girders

**Comment by ghost** [comment]
#14

**Pull request merged**
