### PR TITLE
Added new test objects

### PR DESCRIPTION
**Pull request by DarthCainRor**
Added some objects

### CODE REVIEW

**Comment by DarthCainRor** [comment]
I think this is how this works.

**Comment by Max98** [comment]
I will test your changes tomorrow and see If it's time to merge or no. :)

**Comment by Hiradur** [comment]
Looks good to me.

**Comment by Max98** [comment]
Why isn't the map up to date with Rigs of rods? The current format is < 0.4
It has to be 0.4.

Other than that, your progress is great, but we need to have an actual terrain before adding objects.. :P

**Pull request merged**
